#robot_arm_controller:
# type: "position_controllers/JointTrajectoryController"
# joints: [joint_1, joint_2, joint_3, joint_4, joint_5]

left_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [LHip_yaw, LHip_roll, LHip_pitch, LKnee_pitch, LAnkle_pitch, LAnkle_roll]

right_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [RHip_yaw, RHip_roll, RHip_pitch, RKnee_pitch, RAnkle_pitch, RAnkle_roll]



#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50