controller_list:
  - name: fake_Rarm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - RShoulder_pitch
      - RShoulder_roll
      - RElbow_pitch
  - name: fake_Larm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - LShoulder_pitch
      - LShoulder_roll
      - LElbow_pitch
  - name: fake_Legs_group_controller
    type: $(arg fake_execution_type)
    joints:
      - LHip_roll
      - LHip_pitch
      - LKnee_pitch
      - LAnkle_roll
      - RHip_roll
      - RHip_pitch
      - RKnee_pitch
      - RAnkle_roll
initial:  # Define initial robot poses per group
  - group: Rarm_group
    pose: hi_0_pose